language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hishamss/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true hishamss/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-us-west-2-469047678474"
  bucket_path: "test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
